### ISSUE TITLE
scatter arrow overpowered please nerf

### ISSUE THREAD

**Issue by neko** [hanzo-io/hanzo.js#96] opened 2017-05-08 00:37 UTC
i am sick of being one shot by scatter arrows, please fix this 😡😡😡😡😡

**Comment by davidtai** [comment] 2017-05-08 00:53
I'm sorry to hear that you have encountered this issue.  However, this is intended behavior as Hanzo is supposed to be easy to pick up with little or no experience. 🏹💰💰💰

**Comment by zeekay** [comment] 2017-05-08 18:30
Hanzo's ability takes skill to master -- a deep understanding of the sacred geometry is necessary to land a one-shot kill with it. Closing as wontfix.

**Closed by zeekay** 2017-05-08 18:30 UTC
Labels: wontfix
